[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\scan_engine_custom_device'

[dependencies.niveristand-scan-engine-fxp-libraries]
libraries = ['FXP.llb']
copy_location = 'Custom Device Source'

[dependencies.niveristand-scan-engine-module-libraries]
libraries = ['Modules.lvlibp', 'NI ECAT Remote IO.llb']
copy_location = 'Custom Device Source'

[projects.cd]
path = 'Custom Device Source\Scan Engine.lvproj'

[projects.examples]
path = 'Scripting Examples\Scan Engine Scripting Examples.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'Examples'
type = 'lvBuildSpec'
project = '{examples}'
target = 'My Computer'
build_spec = 'Examples'

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Linux x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'

[[package]]
type = 'nipkg'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Scan Engine' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Scan Engine'
'Built\\Errors' = 'ni-paths-NISHAREDDIR\LabVIEW Run-Time\{veristand_version}\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_scripting'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Scripting\\Scan Engine' = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Scan Engine' 

[[package]]
type = 'nipkg'
control_file = 'control_examples'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Examples\\Scan Engine' = 'ni-paths-LV{veristand_version}DIR\examples\NI VeriStand Custom Devices\Scan Engine' 

[notification]
type = 'teams'
