[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\scan_engine_custom_device'

[dependencies.niveristand-scan-engine-fxp-libraries]
libraries = ['FXP.llb']
copy_location = 'Custom Device Source'

[dependencies.niveristand-scan-engine-module-libraries]
libraries = ['Modules.lvlibp']
copy_location = 'Custom Device Source'

[projects.cd]
path = 'Custom Device Source\Scan Engine.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'Pharlap Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'VxWorks Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'VxWorks'
build_spec = 'Engine Release'
dependency_target = 'VxWorks'

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Linux x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'

[[build.steps]]
name = 'Linux x86 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Linux 32 ARM'
build_spec = 'Engine Release'
dependency_target = 'Linux_32_ARM'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices'
