[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\scan_engine_custom_device'

[dependencies.niveristand-scan-engine-fxp-libraries]
libraries = ['FXP.llb']
copy_location = 'Includes'

[dependencies.niveristand-scan-engine-module-libraries]
libraries = ['Modules.lvlibp', 'NI ECAT Remote IO.llb']
copy_location = 'Includes'

[projects.cd]
path = 'Custom Device Source\Scan Engine.lvproj'

[projects.examples]
path = 'Scripting Examples\Scan Engine Scripting Examples.lvproj'

[[codegen.steps]]
name = 'Delete Scripting API'
type = 'lvRunVi'
vi = 'Custom Device Source\Build VIs\Delete Scripting API.vi'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Windows'
bitness = '64'
bitness_versions = ['2021']

[[build.steps]]
name = 'Application - Revert to Scan Mode'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Revert to Scan Mode'
bitness = '32'
bitness_versions = ['2021']

[[build.steps]]
name = 'Application - Get HW Config'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Get HW Config'
bitness = '32'
bitness_versions = ['2021']

[[build.steps]]
name = 'Application - Check and Download Bitfile'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Check and Download Bitfile'
bitness = '32'
bitness_versions = ['2021']

[[build.steps]]
name = 'Application - Import ESI File'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Import ESI File'
bitness = '32'
bitness_versions = ['2021']

[[build.steps]]
name = 'Application - Read Target ESI Files'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Read Target ESI Files'
bitness = '32'
bitness_versions = ['2021']

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Linux x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'
bitness = '32'
bitness_versions = ['2021']

[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Windows'
bitness = '64'
bitness_versions = ['2021']

[[build.steps]]
name = 'Examples'
type = 'lvBuildSpec'
project = '{examples}'
target = 'My Computer'
build_spec = 'Examples'
bitness = '64'
bitness_versions = ['2021']

[[build.steps]]
name = 'Delete Scripting API'
type = 'lvRunVi'
vi = 'Custom Device Source\Build VIs\Delete Scripting API.vi'

[[package]]
type = 'nipkg'
package_output_dir = 'Built'
multi_bitness = 'true'
multi_bitness_versions = ['2021']

[package.payload_map]
'Built\\Scan Engine' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Scan Engine'
'Built\\Errors' = 'ni-paths-NISHAREDDIR{nipaths_64_bitness_suffix}\LabVIEW Run-Time\{veristand_version}\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_scripting'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Scripting\\Scan Engine' = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\vi.lib\addons\VeriStand Custom Device Scripting APIs\Scan Engine'

[[package]]
type = 'nipkg'
control_file = 'control_examples'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Examples\\Scan Engine' = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\examples\NI VeriStand Custom Devices\Scan Engine'

[notification]
type = 'teams'
